### PR TITLE
Feature/31702819   testimonial slide show

### PR DESCRIPTION
**Pull request by jsons**
This PR includes Testimonial carousel for 31702819 feature

### CODE REVIEW

**Comment by kellypacker** [comment]
@jsons Thanks for this work! I did a bit of work on tightening up the styling because I didn't have specific things to tell you, it was more of an overall massaging and experimenting. I wouldn't normally do that on something you are working on, but it was a tricky layout and since I didn't have specific direction, it was easier to just work through it a bit to move things along. 

I did add a `quoteShort` field in Contentful to shorten some of them and make the display a bit easier. I should have done that earlier to made the content a bit more manageable. So sorry about that. A few notes about naming:

- I think the `CarouselSlideshow` should be renamed to some specific to testimonials since it is specific to that. Maybe `TestimonialSlideShow`. 
- `CarouselTemplate` is also specific to testimonials, so maybe `TestimonialSlide` or something.

**Comment by jsons** [comment]
> 
@kellypacker  no problem!  I will make the requested changes and resubmit.  Thanks for the extra hand.

**Comment by jsons** [comment]
@kellypacker  renamed files as you suggested.   Thanks

**Comment by kellypacker** [comment]
Looks good @jsons. Thanks!

I would just mention that the last commit message "Made suggested changes in review by Kelly." - it would be more informative if it was specific to the changes.

**Comment by jsons** [comment]
> Looks good @jsons. Thanks!
> 
> I would just mention that the last commit message "Made suggested changes in review by Kelly." - it would be more informative if it was specific to the changes.

@kellypacker  no problem, going forward I will be sure to be more specific to the changes.  Thanks for the input, greatly appreciated.

**Pull request merged**
